services:
  api:
    image: api-labeedit:latest
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=teste_db
    ports:
      - 5432:5432